### ISSUE TITLE
Install with npm

### ISSUE THREAD

**Issue by Rey777** [davicotico/jQuery-Menu-Editor#1]
Hello,
I am trying to install this package with npm, the command that i use is:
npm install git+https://github.com/davicotico/jQuery-Menu-Editor.git
But its fail with the follow error:
cb() never called!
I receive this error only with this package.
There is any mistakes or there is another way to install it via npm?

**Comment by Rey777** [comment]
Any fix or suggestion?

**Comment by Rey777** [comment]
Any updates?

**Comment by davicotico** [comment]
Sorry for the delay in replying. It is not yet ready for npm. I'm still working on new features. Tomorrow  I gonna to update the repository with the new features (Buttons "up", "down").
Thanks for the feedback.

**Comment by davicotico** [comment]
The beta version is coming.
npm is not contemplated because there are just few files. The installation is explained in the Readme (basically is just download the files).
