### ISSUE TITLE
Limit to only one level submenu (Parent - child)

### ISSUE THREAD

**Issue by nicolatognon94** [davicotico/jQuery-Menu-Editor#10]
Hello,
I would like to restrict the user to just creating a submenu, then Parent-child. How can I do?

**Comment by davicotico** [comment]
Hi @nicolatognon94 
Sorry, the current version does not support this feature. Will be included your suggestion for the next release.
If you like this tool you can support me by rating the repository. Click on the star button at the top of the page.

**Comment by nicolatognon94** [comment]
@davicotico  Ok, temporarily I've solved using a recursion function in PHP. 
Thanks.
