### ISSUE TITLE
full example php pdo insert or update ?

### ISSUE THREAD

**Issue by Theolodewijk** [davicotico/jQuery-Menu-Editor#11]
Do you have full example php pdo insert or update ?

**Comment by davicotico** [comment]
Hi @Theolodewijk . I don't have, but basically the table schema is:

**menu_id**: int //primary key
**name**: varchar(25) //the menu name
**content**: text // <= THIS IS THE MENU, the json string

You can add more fields according to your needs.

**Comment by webseitz** [comment]
Hi @davicotico, I have written an AJAX-save function to save the whole menu in PHP/MySQL. What is the best way to call this function after every menu change?

**Comment by davicotico** [comment]
Hi @webseitz 
My apologies for the late response.
The short answer is:

```
$('#btnSave').on('click', function () {
    var post = {
      "name": $('#txtName').val(), // the menu name
      "content": editor.getString(); // json output
    };
    $.post(/* your POST request */);
});
```
