### ISSUE TITLE
Menu starting as everyone had children

### ISSUE THREAD

**Issue by piterog** [davicotico/jQuery-Menu-Editor#12]
Hello, im starting the menu like this:

`

        $(document).ready(function(){
                $.ajax({
                    type: "POST",
                    url: "{{ route('menu.getMenu') }}",
                    data: {},
                    success: function(data){
                        arrayjson = data;
                        editor.update();
                        editor.setData(arrayjson);
                        // console.log(data);
                    },error: function(data){
                        console.log(data.responseText);
                    }
                });
            })`

And show as like all the menus had children:

![image](https://user-images.githubusercontent.com/6227151/52052424-7e144080-253d-11e9-9a46-d761f8bb8222.png)

But just the last had an child.
If I drag a menu, the bug was fixed:

![image](https://user-images.githubusercontent.com/6227151/52052477-ab60ee80-253d-11e9-9617-e6ccf9a94f64.png)

**Comment by davicotico** [comment]
Olá @piterog.
Eu falo português então fica mais fácil a nossa comunicação.
Já se passou muito tempo que você apresentou esse problema e provavelmente já tenha resolvido, pelo qual lhe peço desculpas por não ter atendido de forma oportuna.
Para conseguir entender melhor o que é que está acontecendo, vou precisar ver o JSON que você está recebendo via Ajax.
Se você não precisa mais da minha ajuda, por ter já resolvido o seu problema, gostaria que me falasse também para poder fechar a issue aqui no Github.
Fico no aguardo, e qualquer coisa também estou no twitter com o @ **davicodev**

**Comment by davicotico** [comment]
A linha de `editor.update();` não precisa no seu código:

O método update na verdade tem que ser associado a um button, um button no formulário de edição de item que ao clicar atualize o menu editor. Assim:

```
$("#btnUpdate").click(function(){
    editor.update();
});
```
