### ISSUE TITLE
How to allow only one level of nesting?

### ISSUE THREAD

**Issue by neelkanthdaffodil** [davicotico/jQuery-Menu-Editor#14]
This is an awesome plugin but I couldn't find how to disable multilevel nesting and allow only up to one level of nesting.

**Comment by aaron5670** [comment]
Love this plugin too!
And I am also very interested in this feature.. ❤️

**Comment by davicotico** [comment]
> This is an awesome plugin but I couldn't find how to disable multilevel nesting and allow only up to one level of nesting.

@neelkanthdaffodil @aaron5670 

I am working on this feature right now. v1.1.0 is coming, on Sunday 25.

**Comment by davicotico** [comment]
Version 1.1.0 is here [https://github.com/davicotico/jQuery-Menu-Editor/releases/tag/v1.1.0](url)
See the Readme.md example.
