### ISSUE TITLE
touch start event Error.

### ISSUE THREAD

**Issue by InsiteFX** [davicotico/jQuery-Menu-Editor#15]
Getting the following violation running php 7.3.10 with jQuery 3.3.1 on a https:// localhost server.
touchstart

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/574554379596595
jquery-3.3.1.min.js:2

Would be nice if you had the code for saving to a MySQLi database.

**Comment by davicotico** [comment]
Hi @InsiteFX 
My apologies for the late response.
I can not replicate the error that you are reporting.
I don't have a code for saving to a MySQL database for a while. I gonna to made a tutorial including an example with database.
Please follow my Twitter: https://twitter.com/davicodev
