### ISSUE TITLE
drag only in menu 

### ISSUE THREAD

**Issue by jaafarscorpion** [davicotico/jQuery-Menu-Editor#16]
it's possible don't drag in a submenu
like this example
Menu1
 *submenu1
 *Submenu2
Menu2
 *Submenus

**Comment by davicotico** [comment]
Hi @jaafarscorpion 
I am working on a new feature (max depth/level setting) right now. v1.1.0 is coming on Sunday 25.

**Comment by davicotico** [comment]
version 1.1.0 is here [https://github.com/davicotico/jQuery-Menu-Editor/releases/tag/v1.1.0](url) . This version include the maximum level property (maxLevel). More about this on Readme.md example.
