### ISSUE TITLE
Improve programmatic control of the menu

### ISSUE THREAD

**Issue by bididev** [davicotico/jQuery-Menu-Editor#17]
Not currently possible, it heavily relies on markup, and there is little programmatic control. The current way of manipulating items is by getting the existing menu items, merging that with whatever items you wanna add and push the merged data to the editor via `setData`.

Might create a PR for this.

**Comment by davicotico** [comment]
Hi @Raven0us. I appreciate your suggestion and apologize for the delay in responding. For now, I don't have plans to add more features to this library. However, I have worked on and will continue to work on a new project called **Menu Editor** (vanilla javascript), which is much more flexible and easy to customize. [Have a look at it, please](https://davidticona.com/demos/javascript-menu-editor/).
