### ISSUE TITLE
Open to licence change?

### ISSUE THREAD

**Issue by glutamate** [davicotico/jQuery-Menu-Editor#19]
I would love to use this plugin in my project Saltcorn (https://github.com/saltcorn/saltcorn) which is MIT licensed. I don't think I can do this without relicensing my entire project under the GPL - see discussion https://opensource.stackexchange.com/questions/4360/what-are-the-implications-of-licensing-a-javascript-library-under-gpl. Would you be open to changing the licence for jQuery-Menu-Editor to a licence that would allow projects to use it without then needing to apply the GPL to the entire importing project? Of course if you don't want to do this, then I understand.

**Comment by davicotico** [comment]
Hi Tom @glutamate.
Thanks for the link, I didn't know much about it.
I'll change the license over the course of the day. I'll appreciate you giving this repository a star.
I've seen your project, it looks great. I am glad that my work is useful in other projects.
Have a great day.

**Comment by glutamate** [comment]
Thank you so much, this is great news.
