### ISSUE TITLE
Disable drag and drop

### ISSUE THREAD

**Issue by lmassi25** [davicotico/jQuery-Menu-Editor#22]
Hello, thank you very much for this project. I have a doubt. Is it possible to disable drag and drop and manipulate li just by the buttons?

Thanks.

**Comment by davicotico** [comment]
Hi @lmassi25 . Apologies for the delay in responding. This library does not have that feature. I have worked on and will continue to work on a new project called Menu Editor (vanilla javascript). This new project is in version 1.0.0 and is written in Typescript. This version does not yet have buttons for moving items, only drag and drop functionality. [Have a look at it, please](https://davidticona.com/demos/javascript-menu-editor/).
