### ISSUE TITLE
latest bootstrap and fontawesome

### ISSUE THREAD

**Issue by assadnazar** [davicotico/jQuery-Menu-Editor#6]
any plans to add support for latest versions of bootstrap and fontawesome.

**Comment by davicotico** [comment]
@assadnazar Yes I have planned to create a Bootstrap 4 version.
2018-05-31 Version 1.0 First Release
2018-06-30 Version 1.1. (including Bootstrap 4 version)

**Fontawesome.-** I am using the iconset from the plugin Bootstrap-icon-picker by Victor Valencia, so, I gonna to copy the last updated iconset.

Please rate the repository. I would really appreciate it.
Thanks for the feedback.

**Comment by assadnazar** [comment]
I have done some of the lazy work. and its compatible now with the latest versions.
How can I add it to the repo?

**Comment by davicotico** [comment]
@assadnazar 
I just updated the repo with the iconset Fontawesome 4.7.0.
Please update your fork, put your files inside the new folder ```boostrap4``` and make a pull request.
In order to approve the changes, I will first test the code.
Thanks in advance.

**Comment by davicotico** [comment]
Today I release the first version. Actually is v0.9.0
The next release I will include Bootstrap4 support.
