### ISSUE TITLE
Stop drag level

### ISSUE THREAD

**Issue by towsifzilani** [davicotico/jQuery-Menu-Editor#8]
How can i stop dragging the list on three level? i mean to say the parent should have only two level.
![capture](https://user-images.githubusercontent.com/26829777/42418156-5c21c1dc-824f-11e8-9925-46a0afa80777.PNG)

i don't want more than three level like the picture below
![capture_2](https://user-images.githubusercontent.com/26829777/42418163-77aa0388-824f-11e8-94d8-25b045c89217.png)

**Comment by towsifzilani** [comment]
I have solved the problem. Thank you.

**Comment by davicotico** [comment]
Hi @Zilani2013 Sorry for the late response. There are not any option for that feature (for now).

**Comment by nicolatognon94** [comment]
> I have solved the problem. Thank you.
Hello
How did he do? I would have the same problem
